export const GET_ARTICLES_ACTION = 'GET_ARTICLES_ACTION';
export const GET_ARTICLES_ACTION_SUCCESS = 'GET_ARTICLES_ACTION_SUCCESS';
export const GET_ARTICLES_ACTION_FAILURE = 'GET_ARTICLES_ACTION_FAILURE';

export const GET_ARTICLE_DETAIL_ACTION = 'GET_ARTICLE_DETAIL_ACTION';
export const GET_ARTICLE_DETAIL_ACTION_SUCCESS = 'GET_ARTICLE_DETAIL_ACTION_SUCCESS';
export const GET_ARTICLE_DETAIL_ACTION_FAILURE = 'GET_ARTICLE_DETAIL_ACTION_FAILURE';

export const GET_COMMENTS_ACTION = 'GET_COMMENTS_ACTION';
export const GET_COMMENTS_ACTION_SUCCESS = 'GET_COMMENTS_ACTION_SUCCESS';
export const GET_COMMENTS_ACTION_FAILURE = 'GET_COMMENTS_ACTION_FAILURE';

export const UPDATE_COMMENT_ACTION = 'UPDATE_COMMENT_ACTION';
export const UPDATE_COMMENT_ACTION_SUCCESS = 'UPDATE_COMMENT_ACTION_SUCCESS';
export const UPDATE_COMMENT_ACTION_FAILURE = 'UPDATE_COMMENT_ACTION_FAILURE';

export const UPDATE_USER_ACTION = 'UPDATE_USER_ACTION';
export const UPDATE_USER_ACTION_SUCCESS = 'UPDATE_USER_ACTION_SUCCESS';
export const UPDATE_USER_ACTION_FAILURE = 'UPDATE_USER_ACTION_FAILURE';
